name: okan_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  cloud_functions: ^5.6.2
  http: ^1.1.0    
  firebase_messaging: ^15.2.10
  cached_network_image: ^3.3.1
  
  # --- TRADUÇÕES ---
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # --- VÍDEOS ---
  youtube_player_flutter: ^9.0.1
  video_player: ^2.8.1
  chewie: ^1.7.1

  # --- FIREBASE ---
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  firebase_storage: ^12.4.10
  
  
  # --- UTILITÁRIOS E UI ---
  image_picker: ^1.2.1
  google_sign_in: ^6.2.1
  fl_chart: ^1.1.1
  url_launcher: ^6.2.0

  # --- GERÊNCIA DE ESTADO E INJEÇÃO ---
  provider: ^6.1.2
  get_it: ^7.7.0
  
  # --- LÓGICA ---
  equatable: ^2.0.5
  uuid: ^4.4.0
  vibration: ^3.1.5
  flutter_local_notifications: ^21.0.0
  shared_preferences: ^2.5.4
  audioplayers: ^6.6.0
  firebase_app_check: ^0.3.2+10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  # PACOTES DE DESENVOLVIMENTO
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1
  change_app_package_name: ^1.5.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sounds/alarme.mp3

# ----------------------------------------------------------
# CONFIGURAÇÕES (TOTALMENTE À ESQUERDA)
# ----------------------------------------------------------

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_okan.png"
  min_sdk_android: 21
  adaptive_icon_background: "#120E16" # A cor do nosso fundo Roxo Escuro
  adaptive_icon_foreground: "assets/images/logo_okan.png"

flutter_native_splash:
  color: "#120E16"
  image: "assets/images/logo_okan.png"
  android_12:
    image: "assets/images/logo_okan.png"
    color: "#120E16"