// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRbLUy03Y7628Lv3ruMy5PDq0Y3_zwykw',
    appId: '1:1080333508962:web:e93dccc19e32aaaf4ccc3b',
    messagingSenderId: '1080333508962',
    projectId: 'app-academia-2914d',
    authDomain: 'app-academia-2914d.firebaseapp.com',
    storageBucket: 'app-academia-2914d.firebasestorage.app',
    measurementId: 'G-BZBJTDFVR3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAexNOHGsp24JmCmK7JF-ajxv_147sc_U8',
    appId: '1:1080333508962:android:98fb49231c4699c94ccc3b',
    messagingSenderId: '1080333508962',
    projectId: 'app-academia-2914d',
    storageBucket: 'app-academia-2914d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF5kiX0K6uOu7HaE9L5xEu4hfLFUgk8AQ',
    appId: '1:1080333508962:ios:52353ec0642e9b044ccc3b',
    messagingSenderId: '1080333508962',
    projectId: 'app-academia-2914d',
    storageBucket: 'app-academia-2914d.firebasestorage.app',
    iosBundleId: 'com.example.okanApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDF5kiX0K6uOu7HaE9L5xEu4hfLFUgk8AQ',
    appId: '1:1080333508962:ios:52353ec0642e9b044ccc3b',
    messagingSenderId: '1080333508962',
    projectId: 'app-academia-2914d',
    storageBucket: 'app-academia-2914d.firebasestorage.app',
    iosBundleId: 'com.example.okanApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRbLUy03Y7628Lv3ruMy5PDq0Y3_zwykw',
    appId: '1:1080333508962:web:2332ca34271ee70f4ccc3b',
    messagingSenderId: '1080333508962',
    projectId: 'app-academia-2914d',
    authDomain: 'app-academia-2914d.firebaseapp.com',
    storageBucket: 'app-academia-2914d.firebasestorage.app',
    measurementId: 'G-50MNKB2L24',
  );
}
